env:
  browser: true
  node: true
extends:
  - bayathy
  - plugin:tailwindcss/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json

rules:
  "import/no-unresolved": off
  "unicorn/prevent-abbreviations": off
  "react/no-unknown-property": off
  "unicorn/filename-case": off