name: Lint

on:
  pull_request:
    types:
      - opened

jobs:
  CI:
    name: Lint
    if:  startsWith(github.head_ref, 'dev')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install

    - name: Lint code
      run: pnpm lint
    
    - name: Build
      run: pnpm build